public class CVImageWrapper {
    public String contentVersionId {get;set;}
    public String email{get;set;}        
    public String phone{get;set;}
    public String cvId{get;set;}
    public String age{get;set;}
    public String salary{get;set;}
    public String name{get;set;}
    public String status{get;set;}
    public string additionalInfo{get;set;}       
    public List <ID> jobs{get;set;}
}